### PR TITLE
Lena James Slaughter

### PR DESCRIPTION
**Pull request by hannahzacharski**
`/weekend_visitation_as_soon_as_possible_with_Lena_James_Slaughter_signed_by_Judge_Tara_Hagerty % weekend_visitation_as_soon_as_possible_with_Lena_James_Slaughter_signed_by_Judge_Tara_Hagerty /approve`

### CODE REVIEW

**Comment by hannahzacharski** [comment]
`/approve` `/merge`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#105](https://github.com/yegor256/mailanes/issues/105); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:yegor256/mailanes#105` is not assigned, can't get performer

**Comment by 0crat** [comment]
Pull request [#105](https://github.com/yegor256/mailanes/issues/105) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
